'use client';

import { type FormEvent, useState } from 'react';
import type { FamilyCarePatient } from '@/lib/family-care-session';

export function InsuranceCaseModal({ policyId, policyName, patients, onClose, onSaved }: { policyId: string; policyName: string; patients: FamilyCarePatient[]; onClose: () => void; onSaved: () => void }) {
  const [patientId, setPatientId] = useState(patients[0]?.id || ''); const [type, setType] = useState<'authorization' | 'claim'>('authorization'); const [status, setStatus] = useState('En preparación'); const [referenceNumber, setReferenceNumber] = useState(''); const [amount, setAmount] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { const response = await fetch(`/api/family-care/insurance/policies/${encodeURIComponent(policyId)}/cases`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ patientId, type, status, referenceNumber: referenceNumber || null, amount: amount ? Number(amount) : null, submittedAt: status === 'En preparación' ? null : new Date().toISOString() }) }); if (!response.ok) throw new Error(); onSaved(); } catch { setError('No fue posible registrar la gestión. Verifica los datos.'); } finally { setSaving(false); } }
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="profile-modal compact-modal" role="dialog" aria-modal="true" aria-labelledby="insurance-case-title" onMouseDown={(e) => e.stopPropagation()}><button className="close-modal" type="button" onClick={onClose}>×</button><div className="profile-modal-heading"><span>◎</span><div><p className="eyebrow">GESTIÓN DEL SEGURO</p><h2 id="insurance-case-title">Autorización o reclamación</h2></div></div><p className="profile-intro">Vinculada a {policyName} para mantener el seguimiento en un solo lugar.</p><form onSubmit={save}><div className="profile-form-grid"><label className="form-field"><span>Integrante</span><select required value={patientId} onChange={(e) => setPatientId(e.target.value)}>{patients.map((patient) => <option value={patient.id} key={patient.id}>{patient.preferredName || patient.legalName}</option>)}</select></label><label className="form-field"><span>Tipo</span><select value={type} onChange={(e) => setType(e.target.value as typeof type)}><option value="authorization">Autorización</option><option value="claim">Reclamación</option></select></label><label className="form-field"><span>Estado</span><select value={status} onChange={(e) => setStatus(e.target.value)}><option>En preparación</option><option>Presentada</option><option>En revisión</option><option>Aprobada</option><option>Rechazada</option><option>Pagada</option></select></label><label className="form-field"><span>Número de referencia</span><input maxLength={120} value={referenceNumber} onChange={(e) => setReferenceNumber(e.target.value)} /></label><label className="form-field full"><span>Monto reclamado (B/.)</span><input type="number" min="0" max="100000000" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} /></label></div>{error && <p className="share-error" role="alert">{error}</p>}<div className="profile-modal-actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary-action" disabled={saving || !patientId} type="submit">{saving ? 'Guardando…' : 'Guardar gestión'}</button></div></form></section></div>;
}
