'use client';

import { type FormEvent, useEffect, useState } from 'react';

type Setup = { mode: 'simulation' | 'live'; canManage: boolean; callsEnabled: boolean; pushEnabled: boolean; contacts: Array<{ id: string; name: string; relationship: string | null; phone: string; priority: number }> };

export function SosModal({ patientId, person, onNotice, onClose }: { patientId: string | null; person: string; onNotice: (message: string) => void; onClose: () => void }) {
  const [setup, setSetup] = useState<Setup | null>(null); const [configuring, setConfiguring] = useState(false); const [confirming, setConfirming] = useState(false); const [sending, setSending] = useState(false); const [sent, setSent] = useState(false); const [shareLocation, setShareLocation] = useState(false); const [name, setName] = useState(''); const [relationship, setRelationship] = useState(''); const [phone, setPhone] = useState('+507'); const [error, setError] = useState('');
  function load() { fetch('/api/family-care/emergency/setup').then((r) => { if (!r.ok) throw new Error(); return r.json() as Promise<Setup>; }).then(setSetup).catch(() => setError('No fue posible consultar la configuración SOS.')); }
  useEffect(load, []);
  async function addContact(event: FormEvent) { event.preventDefault(); setError(''); try { const response = await fetch('/api/family-care/emergency/contacts', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name, relationship: relationship || null, phone: phone.replace(/[\s()-]/g, ''), priority: (setup?.contacts.length || 0) + 1 }) }); if (!response.ok) throw new Error(); setName(''); setRelationship(''); setPhone('+507'); setConfiguring(false); load(); } catch { setError('Usa un teléfono internacional, por ejemplo +50760000000.'); } }
  function location() { return new Promise<{ latitude: number; longitude: number; accuracy: number } | null>((resolve) => { if (!shareLocation || !navigator.geolocation) return resolve(null); navigator.geolocation.getCurrentPosition((position) => resolve({ latitude: position.coords.latitude, longitude: position.coords.longitude, accuracy: position.coords.accuracy }), () => resolve(null), { enableHighAccuracy: true, timeout: 6000, maximumAge: 0 }); }); }
  async function send() { if (!patientId) return setError('Selecciona el perfil de una persona.'); setSending(true); setError(''); try { const response = await fetch('/api/family-care/emergency/events', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ patientId, location: await location(), note: null }) }); if (!response.ok) throw new Error(); const result = await response.json() as { mode: string; contacts: number; pushesSent: number; callsPlaced: number }; setSent(true); setConfirming(false); onNotice(result.mode === 'simulation' ? `Prueba SOS registrada para ${result.contacts} contacto(s).` : `Alerta enviada: ${result.pushesSent} push y ${result.callsPlaced} llamada(s).`); } catch { setError('No fue posible registrar la alerta. Intenta nuevamente.'); } finally { setSending(false); } }
  const mode = setup?.mode || 'simulation';
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="sos-modal" role="dialog" aria-modal="true" aria-labelledby="sos-title" onMouseDown={(event) => event.stopPropagation()}><button className="close-modal" type="button" onClick={onClose} aria-label="Cerrar">×</button><div className="sos-mark">SOS</div><p className="eyebrow">{mode === 'simulation' ? 'MODO DE PRUEBA SEGURO' : 'ALERTA OPERATIVA'}</p><h2 id="sos-title">Alerta familiar de emergencia</h2><p>{mode === 'simulation' ? 'La prueba deja trazabilidad, pero no realiza llamadas ni envía alertas externas.' : 'Se avisará a los familiares autorizados y se llamará a los contactos configurados.'} Perfil: <strong>{person}</strong>.</p>{configuring ? <form className="sos-contact-form" onSubmit={addContact}><label className="form-field"><span>Nombre</span><input required minLength={2} value={name} onChange={(e) => setName(e.target.value)} /></label><label className="form-field"><span>Relación</span><input value={relationship} onChange={(e) => setRelationship(e.target.value)} placeholder="Hermana, padre…" /></label><label className="form-field full"><span>Teléfono internacional</span><input required type="tel" value={phone} onChange={(e) => setPhone(e.target.value)} /></label><button className="primary-action" type="submit">Guardar contacto</button><button className="cancel-button" type="button" onClick={() => setConfiguring(false)}>Volver</button></form> : <><div className="sos-contact-list">{setup?.contacts.length ? setup.contacts.slice(0, 4).map((contact) => <div key={contact.id}><i>{contact.name.slice(0, 2).toUpperCase()}</i><span><strong>{contact.name}</strong><small>{contact.relationship || 'Contacto'} · {contact.phone}</small></span></div>) : <p>No hay contactos configurados.</p>}</div>{setup?.canManage && <button className="text-button" type="button" onClick={() => setConfiguring(true)}>＋ Agregar contacto</button>}<label className="sos-location"><input type="checkbox" checked={shareLocation} onChange={(e) => setShareLocation(e.target.checked)} /><span>Adjuntar mi ubicación actual a este evento</span></label>{sent ? <div className="test-success" role="status">✓ {mode === 'simulation' ? 'Prueba registrada' : 'Alerta enviada'}</div> : confirming ? <div className="sos-confirm"><strong>Confirma solo si necesitas ayuda</strong><button className="send-sos" disabled={sending || !setup?.contacts.length} type="button" onClick={send}>{sending ? 'Enviando…' : mode === 'simulation' ? 'Confirmar prueba SOS' : 'ENVIAR ALERTA AHORA'}</button></div> : <button className="send-sos" disabled={!patientId || !setup?.contacts.length} type="button" onClick={() => setConfirming(true)}>{setup?.contacts.length ? 'Activar SOS' : 'Agrega un contacto primero'}</button>}<button className="cancel-button" type="button" onClick={onClose}>Cancelar</button></>}{error && <p className="share-error" role="alert">{error}</p>}</section></div>;
}
