import { AppointmentsCard } from '@/components/family-care/appointments-card';
import { PageHeading } from '@/components/family-care/page-heading';
import type { Navigate } from '@/components/family-care/types';
import { metrics, monthlyVisits } from '@/lib/demo-data';

export function Dashboard({ profile, family, onNavigate }: { profile: string; family: boolean; onNavigate: Navigate }) {
  return <>
    <PageHeading eyebrow="MARTES, 8 DE SEPTIEMBRE" title={family ? 'Buenos días, Joel' : `Resumen de ${profile}`} copy={family ? 'Aquí tienes una vista clara de la salud de tu familia.' : 'Consulta próximos controles, evolución y documentos importantes.'} action={<div className="period-control"><button type="button" aria-label="Año anterior">‹</button><span>Resumen 2026</span><button type="button" aria-label="Año siguiente">›</button></div>} />
    <section className="metric-grid" aria-label="Resumen anual">{metrics.map((metric) => <article className={`metric-card ${metric.tone}`} key={metric.label}><div className="metric-topline"><span className="metric-dot" /><span>Este año</span></div><strong>{metric.value}</strong><h2>{metric.label}</h2><p>{metric.detail}</p></article>)}</section>
    <section className="dashboard-grid"><div className="primary-column">
      <article className="panel care-panel"><div className="panel-heading"><div><p className="eyebrow">SEGUIMIENTO ACTIVO</p><h2>Planes de cuidado</h2></div><button type="button" className="text-button" onClick={() => onNavigate('expedientes')}>Ver todos</button></div><div className="care-list">
        <button className="care-item daughter" type="button" onClick={() => onNavigate('laboratorios')}><span className="care-person"><span className="avatar avatar-sofia">SC</span><span><strong>Sofía</strong><small>Seguimiento hematológico</small></span></span><span className="care-reading"><small>Última hemoglobina</small><strong>10.8 <small>g/dL</small></strong><em>↑ 1.4 desde julio</em></span><span className="care-next"><small>Próximo control</small><strong>12 sep.</strong><small>en 4 días</small></span><span className="round-link">›</span></button>
        <button className="care-item wife" type="button" onClick={() => onNavigate('expedientes')}><span className="care-person"><span className="avatar avatar-maria">MC</span><span><strong>María</strong><small>Artritis reumatoide</small></span></span><span className="care-reading"><small>Estado reciente</small><strong className="status-stable">Estable</strong><em>Sin brotes en 21 días</em></span><span className="healwave-source"><i className="source-pulse" /><span><small>Fuente externa</small><strong>Healwave</strong><small>Solo lectura</small></span></span><span className="round-link">›</span></button>
      </div></article>
      <article className="panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">ACTIVIDAD FAMILIAR</p><h2>Atención médica durante el año</h2></div><div className="legend"><span /> Consultas y controles</div></div><div className="bar-chart" aria-label="Gráfica mensual de consultas y controles">{monthlyVisits.map((value, index) => <div className="bar-column" key={index}><div className="bar-track"><div className="bar-fill" style={{ height: `${value * 6}px` }} /></div><span>{'EFMAMJJASOND'[index]}</span></div>)}</div></article>
    </div><aside className="secondary-column"><AppointmentsCard onOpen={() => onNavigate('calendario')} /><article className="panel quick-panel"><p className="eyebrow">ACCESO RÁPIDO</p><h2>¿Qué deseas registrar?</h2><div className="quick-grid"><button type="button" onClick={() => onNavigate('expedientes')}><span>＋</span>Consulta</button><button type="button" onClick={() => onNavigate('laboratorios')}><span>↥</span>Laboratorio</button><button type="button" onClick={() => onNavigate('medicamentos')}><span>◷</span>Medicamento</button><button type="button" onClick={() => onNavigate('documentos')}><span>▣</span>Documento</button></div></article></aside></section>
  </>;
}
