'use client';

import { type FormEvent, useCallback, useEffect, useState } from 'react';
import { PageHeading } from '@/components/family-care/page-heading';
import { InsuranceCaseModal } from '@/components/family-care/insurance-case-modal';
import type { Notify } from '@/components/family-care/types';
import type { FamilyCarePatient } from '@/lib/family-care-session';

type Policy = { id: string; insurerName: string; planName: string | null; policyNumberMasked: string | null; renewalDate: string | null; assistancePhone: string | null; beneficiaries: Array<{ patientId: string; patientName: string }>; cases: Array<{ id: string; patientName: string; type: 'authorization' | 'claim'; status: string; referenceNumber: string | null }> };
type InsuranceData = { canManage: boolean; policies: Policy[] };

function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat('es-PA', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${value}T12:00:00Z`)) : 'No registrada'; }

function PolicyModal({ patients, onClose, onSaved }: { patients: FamilyCarePatient[]; onClose: () => void; onSaved: () => void }) {
  const [insurerName, setInsurerName] = useState(''); const [policyNumber, setPolicyNumber] = useState(''); const [planName, setPlanName] = useState(''); const [renewalDate, setRenewalDate] = useState(''); const [assistancePhone, setAssistancePhone] = useState(''); const [selected, setSelected] = useState<string[]>(patients.map((p) => p.id)); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function save(event: FormEvent) { event.preventDefault(); if (!selected.length) return setError('Selecciona al menos un beneficiario.'); setSaving(true); setError(''); try { const response = await fetch('/api/family-care/insurance/policies', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ insurerName, policyNumber, planName: planName || null, effectiveDate: null, renewalDate: renewalDate || null, assistancePhone: assistancePhone || null, notes: null, beneficiaries: selected.map((patientId) => ({ patientId, memberNumber: null })) }) }); if (!response.ok) throw new Error(); onSaved(); } catch { setError('No fue posible guardar la póliza. Verifica los datos.'); } finally { setSaving(false); } }
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="profile-modal compact-modal" role="dialog" aria-modal="true" aria-labelledby="policy-title" onMouseDown={(e) => e.stopPropagation()}><button className="close-modal" type="button" onClick={onClose} aria-label="Cerrar">×</button><div className="profile-modal-heading"><span>▣</span><div><p className="eyebrow">NUEVA PÓLIZA</p><h2 id="policy-title">Cobertura familiar</h2></div></div><p className="profile-intro">El número se cifra antes de guardarse y solo se muestra parcialmente.</p><form onSubmit={save}><div className="profile-form-grid"><label className="form-field"><span>Aseguradora</span><input required minLength={2} value={insurerName} onChange={(e) => setInsurerName(e.target.value)} /></label><label className="form-field"><span>Número de póliza</span><input required minLength={3} autoComplete="off" value={policyNumber} onChange={(e) => setPolicyNumber(e.target.value)} /></label><label className="form-field"><span>Plan</span><input value={planName} onChange={(e) => setPlanName(e.target.value)} /></label><label className="form-field"><span>Renovación</span><input type="date" value={renewalDate} onChange={(e) => setRenewalDate(e.target.value)} /></label><label className="form-field full"><span>Teléfono de asistencia</span><input type="tel" value={assistancePhone} onChange={(e) => setAssistancePhone(e.target.value)} placeholder="+507…" /></label></div><fieldset className="reminder-options"><legend>Beneficiarios</legend>{patients.map((patient) => <label key={patient.id}><input type="checkbox" checked={selected.includes(patient.id)} onChange={() => setSelected((current) => current.includes(patient.id) ? current.filter((id) => id !== patient.id) : [...current, patient.id])} />{patient.preferredName || patient.legalName}</label>)}</fieldset>{error && <p className="share-error" role="alert">{error}</p>}<div className="profile-modal-actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary-action" disabled={saving} type="submit">{saving ? 'Guardando…' : 'Guardar póliza'}</button></div></form></section></div>;
}

export function Insurance({ patients, onNotice }: { patients: FamilyCarePatient[]; onNotice: Notify }) {
  const [data, setData] = useState<InsuranceData | null>(null); const [open, setOpen] = useState(false); const [casePolicy, setCasePolicy] = useState<Policy | null>(null); const [revision, setRevision] = useState(0);
  const load = useCallback(() => { fetch('/api/family-care/insurance').then((r) => { if (!r.ok) throw new Error(); return r.json(); }).then(setData).catch(() => setData(null)); }, []);
  useEffect(() => { load(); }, [load, revision]); const policy = data?.policies[0];
  return <><PageHeading eyebrow="SEGUROS" title="Pólizas y coberturas" copy="Vigencia, beneficiarios, autorizaciones, reclamaciones y teléfonos de asistencia." action={<button className="primary-action" type="button" disabled={!patients.length || data?.canManage === false} onClick={() => setOpen(true)}>＋ Agregar póliza</button>} />{!policy ? <section className="empty-state insurance-empty"><span>▣</span><h2>Añade tu primera póliza</h2><p>Centraliza cobertura y beneficiarios sin dejar números sensibles en texto visible.</p><button className="primary-action" type="button" disabled={!patients.length} onClick={() => setOpen(true)}>Registrar póliza</button></section> : <div className="content-grid wide-main"><section className="insurance-card"><div><p>SEGURO MÉDICO FAMILIAR</p><h2>{policy.planName || policy.insurerName}</h2><span>Póliza {policy.policyNumberMasked || 'cifrada'}</span></div><strong>{policy.renewalDate && policy.renewalDate < new Date().toISOString().slice(0, 10) ? 'Revisar vigencia' : 'Vigente'}</strong><footer><span>Renovación<br/><b>{formatDate(policy.renewalDate)}</b></span><span>Beneficiarios<br/><b>{policy.beneficiaries.length}</b></span><span>Asistencia<br/><b>{policy.assistancePhone || 'No registrada'}</b></span></footer></section><aside className="panel side-summary"><p className="eyebrow">GESTIONES</p><h2>Actividad del seguro</h2>{policy.cases.length ? policy.cases.slice(0, 4).map((item) => <div className="insurance-case" key={item.id}><strong>{item.type === 'claim' ? 'Reclamación' : 'Autorización'} · {item.patientName}</strong><span>{item.status}{item.referenceNumber ? ` · ${item.referenceNumber}` : ''}</span></div>) : <p className="muted-copy">Aún no hay autorizaciones ni reclamaciones registradas.</p>}<button className="insurance-action" type="button" onClick={() => setCasePolicy(policy)}>Registrar gestión<span>›</span></button></aside></div>}{data && data.policies.length > 1 && <section className="panel policy-list"><p className="eyebrow">OTRAS COBERTURAS</p>{data.policies.slice(1).map((item) => <button type="button" key={item.id} onClick={() => setCasePolicy(item)}><strong>{item.insurerName}</strong><span>{item.planName || 'Plan sin nombre'} · {item.policyNumberMasked}</span></button>)}</section>}{open && <PolicyModal patients={patients} onClose={() => setOpen(false)} onSaved={() => { setOpen(false); setRevision((v) => v + 1); onNotice('Póliza cifrada y guardada correctamente.'); }} />}{casePolicy && <InsuranceCaseModal policyId={casePolicy.id} policyName={casePolicy.planName || casePolicy.insurerName} patients={patients} onClose={() => setCasePolicy(null)} onSaved={() => { setCasePolicy(null); setRevision((v) => v + 1); onNotice('Gestión de seguro registrada.'); }} />}</>;
}
