import { PageHeading } from '@/components/family-care/page-heading';
import type { Notify } from '@/components/family-care/types';
import type { FamilyCarePatient } from '@/lib/family-care-session';

const timeline = [
  { date: '27 AGO 2026', title: 'Hemograma de control', meta: 'Laboratorio · Lia Joan', copy: 'Resultados estructurados y documento original asociados al seguimiento hematológico.', tag: 'Laboratorio' },
  { date: '14 AGO 2026', title: 'Consulta de reumatología', meta: 'Reumatología · Eileen Patricia', copy: 'Resumen proveniente de Healwave. Fuente externa marcada como solo lectura.', tag: 'Healwave' },
  { date: '03 JUL 2026', title: 'Hospitalización', meta: 'Hematología pediátrica · Lia Joan', copy: 'Episodio con ingreso, alta, indicaciones, medicamentos y documentos relacionados.', tag: 'Hospitalización' },
];

function displayDate(value: string | null) {
  if (!value) return 'No registrada';
  return new Intl.DateTimeFormat('es-PA', { dateStyle: 'medium', timeZone: 'America/Panama' }).format(new Date(value + 'T12:00:00Z'));
}

export function Records({ profile, patient, onNotice, onShare, onEdit, canShare, canEdit }: { profile: string; patient?: FamilyCarePatient; onNotice: Notify; onShare: () => void; onEdit: () => void; canShare: boolean; canEdit: boolean }) {
  const share = () => canShare ? onShare() : onNotice('Selecciona un perfil protegido con permiso para compartir.', 'warning');
  const edit = () => canEdit ? onEdit() : onNotice('Selecciona un perfil protegido con permiso de edición.', 'warning');
  return <><PageHeading eyebrow="EXPEDIENTE LONGITUDINAL" title={`Historia clínica de ${profile}`} copy="Consultas, hospitalizaciones, especialistas, diagnósticos y archivos en una sola línea de tiempo." action={<div className="heading-actions"><button className="secondary-action" onClick={edit} type="button">✎ Editar perfil</button><button className="secondary-action" onClick={share} type="button">↗ Compartir</button><button className="primary-action" onClick={() => onNotice('El formulario de atenciones será el siguiente módulo persistente.')} type="button">＋ Registrar atención</button></div>} /><div className="content-grid wide-main"><section className="panel module-panel"><div className="filter-row"><button className="filter-pill active" type="button">Todo</button><button className="filter-pill" type="button">Consultas</button><button className="filter-pill" type="button">Hospitalizaciones</button><button className="filter-pill" type="button">Especialistas</button></div><div className="timeline">{timeline.map((entry) => <article className="timeline-item" key={entry.title}><div className="timeline-dot" /><div><span>{entry.date}</span><h2>{entry.title}</h2><p>{entry.meta}</p><small>{entry.copy}</small></div><em>{entry.tag}</em></article>)}</div></section><aside className="panel side-summary">{patient ? <><p className="eyebrow">FICHA ESENCIAL</p><h2>{patient.legalName}</h2><div className="profile-summary-row"><span>Nacimiento</span><strong>{displayDate(patient.birthDate)}</strong></div><div className="profile-summary-row"><span>Grupo sanguíneo</span><strong>{patient.bloodType || 'No registrado'}</strong></div><div className="profile-summary-block"><span>Alergias</span><p>{patient.allergiesSummary || 'No registradas'}</p></div><div className="profile-summary-block emergency"><span>Resumen para emergencias</span><p>{patient.emergencySummary || 'Pendiente de completar'}</p></div><span className={patient.canShare ? 'permission-status enabled' : 'permission-status'}>{patient.canShare ? '✓ Enlaces médicos habilitados' : 'Enlaces médicos deshabilitados'}</span></> : <><p className="eyebrow">COBERTURA DEL EXPEDIENTE</p><h2>Información clínica completa</h2>{['Antecedentes y alergias', 'Diagnósticos y condiciones', 'Consultas de cualquier especialidad', 'Hospitalizaciones y procedimientos', 'Recetas, referencias y adjuntos'].map((item) => <p className="check-row" key={item}><span>✓</span>{item}</p>)}</>}<div className="readonly-note"><strong>Healwave</strong><p>La futura integración consultará una fuente secundaria de solo lectura. Family Care nunca escribirá en producción.</p></div></aside></div></>;
}
